version: '3'

services:
  django:
    build: ./delta-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  client:
    build: ./delta-frontend
    ports:
      - 3000:3000